[package]
name = "guitar-midi-mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.5.1"
gilrs = "0.11.0"
midir = "0.10.3"
